export const CHARACTER_DATA_GET = "getCharacterData";
export const ITEM_DATA_GET = "getItemData";
export const ITEM_USE_DATA_GET = "getItemUseData";
export const ITEM_FORMULA_DATA_GET = "getItemFormulaData";
export const EQUIPMENT_DATA_GET = "getEquipmentData";
export const MATERIAL_PLANNER_INIT = "initMaterialPlanner";
export const OPERATOR_PLAN_CHANGE = "changeOperatorPlan";
export const OPERATOR_PLAN_SET_TARGET_EQUAL_CURRENT =
  "setTargetOperatorPlanToCurrent";
export const OPERATOR_PLAN_SET_TARGET_TO_MAX = "setTargetOperatorPlanToMax";
export const OPERATOR_PLAN_SET = "setOperatorPlan";
export const OPERATOR_PLANS_SET = "setOperatorPlans";
export const TARGET_OPERATOR_CHANGE = "changeTargetOperator";
export const CURRENT_ITEM_CHANGE = "changeCurrentItem";
export const CHARACTER_CLASS_GET = "getCharacterClass";
export const ITEM_FORMULA_CHANGE = "changeItemFormulaValue";
export const SELECTED_OPERATOR_IDS_CHANGE = "changeSelectedOperatorIds";
export const SELECTED_OPERATOR_TOGGLE = "toggleSelectOperator";
export const GAME_DATA_GET = "getGameData";
